# Generated by Django 4.2.3 on 2023-07-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='содержимое статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/media/', verbose_name='изображение')),
                ('views', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('publish_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ('views',),
            },
        ),
    ]
