# Generated by Django 4.2.3 on 2023-07-25 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailling_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.TimeField(auto_now=True, verbose_name='время рассылки')),
                ('frequency', models.CharField(choices=[('daily', 'ежедневно'), ('weekly', 'еженедельно'), ('monthly', 'ежемесячно')], max_length=15, verbose_name='периодичность рассылки')),
                ('status', models.CharField(choices=[('created', 'создана'), ('started', 'запущена'), ('completed', 'выполнена')], default='created', max_length=15, verbose_name='статус рассылки')),
                ('client', models.ManyToManyField(to='mailling_list.client', verbose_name='клиенты')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='тело письма')),
                ('mailling_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailling_list.mailling_list', verbose_name='настройки рассылки')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateField(auto_now=True, verbose_name='дата последней попытки')),
                ('status', models.CharField(choices=[('success', 'успешно'), ('error', 'ошибка')], max_length=15, verbose_name='статус попытки')),
                ('responce', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('mailling_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailling_list.mailling_list', verbose_name='Письмо для рассылки')),
            ],
        ),
    ]
