# Generated by Django 4.2.3 on 2023-07-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailling_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mailling_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailling_list.mailling_list', verbose_name='настройки рассылки'),
        ),
    ]
